import type { NextPage } from "next";
import React, { useState, useRef,useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MapChart from "../components/MapChart";
import cursor from "../public/cursors/cursor.png";

interface StateProps {
  stateData: any
}
const Home: React.FC<StateProps> = ({stateData}) => {
  useEffect(()=> {
    console.log(stateData)
  })
   return (
    <div
      className={styles.container}
      style={{ cursor: `url(${cursor}), auto` }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          <a href="#">Killing statistic in USA</a>
        </h3>
        <p style={{marginBottom:0,color:'#1c352d',fontFamily: 'Edu TAS Beginner'}}>2015-2017 years</p>
        <p style={{marginBottom:0,color:'#1c352d',fontFamily: 'Edu TAS Beginner',fontSize:14,letterSpacing:3}}>Click or hover dot for info</p>
        <MapChart stateData={stateData}  />
      </main>
      
    </div>
  );
};

export async function getServerSideProps() {
  //http://localhost:3000
  const state_res = await fetch('https://statistic-six.vercel.app/api/states')
  const stateData = await state_res.json()
  //const announcements = await loadPosts()
  //announcements?filters[category][$eq]=cat
  //announcements?filters[category][$eq]=dog&filters[category][$eq]=cat
  //announcements?filters[title][$contains]=
  return {
    props: {
      stateData
      
    }
  }
}

export default Home;
